name: Other issue
description: Template for any other issues relating to this project
title: "[Other]: "

body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: Briefly describe the issue or suggestion you'd like to raise.
    validations:
      required: true

- type: textarea
  id: importance
  attributes:
    label: Why this is important?
    description: Describe how this affects you and / or others who may use the project. What would happen if this wasn't addressed?
    validations:
      required: true
